"""Write ``docs/data_status.md``: what is listed, what has been received, what is missing.

Combines the listing CSVs, the NIFTY 50 universe and the intake manifest. The report contains
only symbols, company names, reporting years, taxonomy versions and file names - no filing
content - so it is safe to commit.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd

from ingestion import config
from ingestion.discover import KNOWN_UNAVAILABLE, load_listings
from ingestion.intake import read_manifest
from ingestion.universe import load_universe

RECEIVED = "received"
LISTED_UNAVAILABLE = "listed_unavailable"
MISSING = "missing"


def filing_status(listing: pd.DataFrame, manifest: pd.DataFrame) -> pd.DataFrame:
    """Listing rows plus ``status`` and ``taxonomy_version`` (from the manifest, if received)."""
    received = manifest.drop_duplicates("filing_id").set_index("filing_id")["taxonomy_version"]
    df = listing.copy()
    df["taxonomy_version"] = df["filing_id"].map(received)
    df["status"] = MISSING
    df.loc[df["xbrl_file_name"].isin(KNOWN_UNAVAILABLE), "status"] = LISTED_UNAVAILABLE
    df.loc[df["taxonomy_version"].notna(), "status"] = RECEIVED
    return df


def _display_name(names: pd.Series) -> str:
    """Latest company name, skipping ones with U+FFFD (NSE's CSV has some, e.g. SBIN)."""
    clean = [n for n in names if "�" not in n]
    return (clean or list(names))[-1]


def _years(series: pd.Series) -> str:
    return ", ".join(sorted(series)) or "-"


def build_report(
    listing: pd.DataFrame,
    universe: pd.DataFrame,
    manifest: pd.DataFrame,
    inbox_files: list[str] | None = None,
    today: date | None = None,
) -> str:
    """Return the markdown report."""
    status = filing_status(listing, manifest)
    universe_symbols = set(universe["symbol"])
    listed_symbols = set(status["symbol"])
    today = today or date.today()

    lines = [
        "# Data status",
        "",
        f"_Generated by `python -m ingestion.todo` on {today.isoformat()}. "
        "Sources: listing CSVs in `data/raw/listing/`, NIFTY 50 list in `data/raw/reference/`, "
        "intake manifest `data/raw/manifest.csv`. Names, years and file names only._",
        "",
        "## Totals",
        "",
        "| Item | Count |",
        "|---|---:|",
        f"| Companies in universe (NIFTY 50 list) | {len(universe_symbols)} |",
        f"| Companies with a listing CSV | {len(listed_symbols)} |",
        f"| - of which in universe | {len(listed_symbols & universe_symbols)} |",
        f"| - of which not in universe | {len(listed_symbols - universe_symbols)} |",
        f"| Universe companies without a listing CSV | {len(universe_symbols - listed_symbols)} |",
        f"| Listed filings | {len(status)} |",
        f"| Received (in manifest) | {int((status['status'] == RECEIVED).sum())} |",
        f"| Listed but unavailable at source | "
        f"{int((status['status'] == LISTED_UNAVAILABLE).sum())} |",
        f"| Missing (still to download) | {int((status['status'] == MISSING).sum())} |",
        f"| Non-standard reporting periods | {int(status['is_non_standard_period'].sum())} |",
        f"| Files waiting in inbox | {len(inbox_files or [])} |",
        "",
        "## Per company",
        "",
        "| Symbol | Company | In universe | Years listed | Years received | Missing "
        "| Taxonomy versions |",
        "|---|---|---|---|---|---|---|",
    ]
    for symbol, grp in status.groupby("symbol", sort=True):
        received = grp[grp["status"] == RECEIVED]
        missing = [
            r.reporting_year_label + (f" ({r.status})" if r.status != MISSING else "")
            for r in grp[grp["status"] != RECEIVED].itertuples()
        ]
        versions = ", ".join(sorted(received["taxonomy_version"].unique())) or "-"
        lines.append(
            f"| {symbol} | {_display_name(grp['company_name'])} | "
            f"{'yes' if symbol in universe_symbols else '**no**'} | "
            f"{len(grp)}: {_years(grp['reporting_year_label'])} | "
            f"{len(received)}: {_years(received['reporting_year_label'])} | "
            f"{', '.join(missing) or '-'} | {versions} |"
        )

    lines += ["", "## Listed but unavailable at source", ""]
    unavailable = status[status["status"] == LISTED_UNAVAILABLE]
    if unavailable.empty:
        lines.append("None.")
    else:
        lines += ["| Symbol | Reporting year | File | Note |", "|---|---|---|---|"]
        lines += [
            f"| {r.symbol} | {r.reporting_year_label} | `{r.xbrl_file_name}` "
            f"| {KNOWN_UNAVAILABLE[r.xbrl_file_name]} |"
            for r in unavailable.itertuples()
        ]

    lines += ["", "## Universe companies with no listing CSV", ""]
    no_listing = universe[~universe["symbol"].isin(listed_symbols)]
    if no_listing.empty:
        lines.append("None.")
    else:
        lines += ["| Symbol | Company | Industry |", "|---|---|---|"]
        lines += [
            f"| {r.symbol} | {r.company_name} | {r.industry} |" for r in no_listing.itertuples()
        ]

    lines += [
        "",
        "## Non-standard reporting periods",
        "",
        "Flag rule: `fy_to - fy_from != 1` on the listing years. It cannot see periods whose "
        "length differs inside the same year span (e.g. NESTLEIND 2023-2024, a 15-month period "
        "starting 2023-01-01 in the XBRL); true period lengths come from XBRL contexts in the "
        "parser.",
        "",
    ]
    odd = status[status["is_non_standard_period"]]
    if odd.empty:
        lines.append("None flagged by the listing years.")
    else:
        lines += [f"- {r.symbol} {r.reporting_year_label}" for r in odd.itertuples()]

    lines += [
        "",
        "## Received filings per taxonomy version",
        "",
        "| Taxonomy version | Filings |",
        "|---|---:|",
    ]
    by_version = status.loc[status["status"] == RECEIVED, "taxonomy_version"].value_counts()
    lines += [f"| {v} | {n} |" for v, n in sorted(by_version.items())]
    lines.append(f"| **Total** | **{int(by_version.sum())}** |")
    return "\n".join(lines) + "\n"


def write_report(out_path: Path = config.DATA_STATUS_MD) -> str:
    report = build_report(
        listing=load_listings(),
        universe=load_universe(),
        manifest=read_manifest(),
        inbox_files=sorted(p.name for p in config.XBRL_INBOX_DIR.glob("*.xml")),
    )
    out_path.write_text(report, encoding="utf-8", newline="\n")
    return report


def main() -> None:
    report = write_report()
    totals = report.split("## Per company")[0].split("## Totals")[1]
    print(totals.strip())
    print(f"-> {config.display_path(config.DATA_STATUS_MD)}")


if __name__ == "__main__":
    main()
