"""Regenerate the KPI table in docs/kpi_definitions.md from the KPI catalogue seed.

    python scripts/build_kpi_docs.py           # rewrite the table
    python scripts/build_kpi_docs.py --check   # exit 1 if the table is out of date (used by pytest)

dbt/seeds/kpi_catalogue.csv is the single source of truth for the KPIs of fct_company_year:
name, label, formula, unit, direction, whether the value may be published and a plain-English
definition. Only the part of the page between the two markers is generated; the hand-written
prose around it is left untouched.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEED = ROOT / "dbt" / "seeds" / "kpi_catalogue.csv"
DOC = ROOT / "docs" / "kpi_definitions.md"
START = "<!-- KPI_TABLE:START (generated by scripts/build_kpi_docs.py - do not edit by hand) -->"
END = "<!-- KPI_TABLE:END -->"

BETTER = {"lower_better": "Lower", "higher_better": "Higher", "context": "Context", "n/a": "-"}
HEADERS = [
    "KPI column",
    "Label",
    "Formula",
    "Unit",
    "Better",
    "Public",
    "Benchmarked",
    "Plain-English definition",
]


def cell(text: str) -> str:
    """Make a value safe for a Markdown table cell."""
    return text.replace("|", "\\|").strip()


def build_table(seed: Path = SEED) -> str:
    with seed.open(encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    lines = [
        f"{len(rows)} KPIs, {sum(r['public_safe'] == 'true' for r in rows)} public, "
        f"{sum(r['is_benchmarked'] == 'true' for r in rows)} benchmarked against peers.",
        "",
        "| " + " | ".join(HEADERS) + " |",
        "|" + "---|" * len(HEADERS),
    ]
    for r in rows:
        cells = [
            f"`{r['kpi_name']}`",
            cell(r["label"]),
            cell(r["formula_text"]),
            cell(r["unit"]),
            BETTER.get(r["direction"], r["direction"]),
            "yes" if r["public_safe"] == "true" else "no",
            "yes" if r["is_benchmarked"] == "true" else "",
            cell(r["definition_plain"]),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def render(doc_text: str, table: str) -> str:
    """Return the page with the generated block replaced."""
    if START not in doc_text or END not in doc_text:
        raise SystemExit(f"markers not found in {DOC.name}: add {START!r} and {END!r}")
    head, rest = doc_text.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n\n{table}\n\n{END}{tail}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the table is out of date")
    args = parser.parse_args(argv)

    raw = DOC.read_bytes().decode("utf-8")
    newline = "\r\n" if "\r\n" in raw else "\n"
    current = raw.replace("\r\n", "\n")
    updated = render(current, build_table())
    if args.check:
        if updated != current:
            print(f"{DOC.name} is out of date: run python scripts/build_kpi_docs.py")
            return 1
        return 0
    if updated != current:
        DOC.write_bytes(updated.replace("\n", newline).encode("utf-8"))
        print(f"updated {DOC.relative_to(ROOT)}")
    else:
        print(f"{DOC.relative_to(ROOT)} already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
